name: Build Portable C Kids Learn

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create portable python
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          .\install_portable_python.ps1

      - name: Create portable launch file
        shell: pwsh
        run: |
          Set-Content -Path launch-win.bat -Value "@echo off`ncd /d ""%~dp0""`npython-win\python.exe run.py"

      - name: Remove unnecessary files
        shell: pwsh
        run: |
          Write-Host "> Cleaning unnecessary files..."
          $toRemove = @('.git', '.github', '__pycache__', 'subscripts', '.gitignore', 'README.md', 'requirements.txt', 'install_portable_python.ps1')
          foreach ($item in $toRemove) {
            if (Test-Path $item) { Remove-Item -Recurse -Force $item -ErrorAction SilentlyContinue }
          }

      - name: Move files to portable directory and create archive
        shell: pwsh
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          echo "REPO_NAME=$repoName" >> $env:GITHUB_ENV
          New-Item -ItemType Directory -Path $repoName | Out-Null
          Get-ChildItem -Force | Where-Object { $_.Name -ne $repoName } | Move-Item -Destination $repoName
          Write-Host "> Creating application.zip..."
          Compress-Archive -Path $repoName -DestinationPath "application.zip" -Force

      - name: Delete old Latest release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to 'Latest' release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: application.zip
          asset_name: ${{ github.event.repository.name }}.zip
          tag: latest
          release_name: Latest
          overwrite: true
          body: "Automated latest build for ${{ github.sha }}"

